### ISSUE TITLE
Context does not work in some cases

### ISSUE THREAD

**Issue by billbarni** [pinussilvestrus/camunda-modeler-webpack-plugins#1]
I can't seem to make React-Icons IconContext work.

React cannot find itself.

I am also unable to render things to HTML (ReactDOMServer is never found).

**Comment by pinussilvestrus** [comment]
Hi @billbarni, thanks for the request. Can you maybe add an example of the broken behavior?

**Comment by billbarni** [comment]
@pinussilvestrus Thank you for the attention:

https://github.com/camunda/camunda-modeler-plugin-example/issues/27

Here follows the bug also opened in 'camunda-modeler-plugin-example'. There is an attached minimal reproduction repository.

Thank you again.

**Comment by pinussilvestrus** [comment]
Thanks for sharing! The `diagram-js` [Palette](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/palette/Palette.js#L255) is not supporting anything besides basic HTML to render entries, no React component or something else. 

So you are right in your assumption that you would need to convert this to basic HTML. Not sure whether that should be the use case of this plugin, as it solves basic Camunda Modeler plugins.

`ReactDOMServer` is likely not working here, as Camunda Modeler plugins only work in the browser. Are you forced to use `react-icons` or could you simply include the raw SVG icon?

**Comment by billbarni** [comment]
Why if I use a manual webpack config and `preact-render-to-string` the react-icon works? But if I do that the `registerClientPlugin` will then fail?

**Comment by pinussilvestrus** [comment]
> `registerClientPlugin` will then fail?

Can you explain what fails in particular? I think an error message would be helpful here.

**Comment by billbarni** [comment]
https://github.com/billbarni/camunda-modeler-plugin-react-test/tree/webpack_config_test

new branch with "manual" config immitating yours in webpack... without the client plugin... the render works.

please "npm i" and "npm run dev" to clean up dist..

If I activate the 'client' plugin:

![image](https://user-images.githubusercontent.com/21037830/232598188-7af89e5f-5cab-449c-8c39-0e610d419672.png)

**Comment by pinussilvestrus** [comment]
Thanks for sharing, really appreciating it! I'll try to have a lookwhat's going on once I find the time. It's a side project, so I can't guarantee a time line here.

In the meanwhile, can you share which plugins did you try? From your explanations

```js
const ClientExtensionWebpackPlugin = require("camunda-modeler-webpack-plugins").ClientExtensionWebpackPlugin;

module.exports = {
  plugins: [
    new ClientExtensionWebpackPlugin()
  ]
};
```

What else did you include in your webpack config? [Is it this one](https://github.com/billbarni/camunda-modeler-plugin-react-test/blob/main/webpack.config.js)?

**Comment by pinussilvestrus** [comment]
Hi @billbarni I just remembered the fact that we recently moved this project to https://github.com/camunda/camunda-modeler-webpack-plugin, which slight changes in the architecture and a first released version `v0.1.0`. 

I'm sorry for the confusion. Please try out the correct plugin and let me know whether it works for you. If not, there are some [configuration options](https://github.com/camunda/camunda-modeler-webpack-plugin#configuration) to try out. The following with your posted webpack config works well for me locally and without the error you described.

```js
const CamundaModelerWebpackPlugin = require('camunda-modeler-webpack-plugin');

module.exports = {
 ...
  plugins: [
    new CamundaModelerWebpackPlugin({
      type: 'react'
    })
  ]
};
```

**Comment by pinussilvestrus** [comment]
Added a note to this project that it is deprecated via https://github.com/pinussilvestrus/camunda-modeler-webpack-plugins/commit/f34cac9632758d937a7504c003a281a0d894a597

**Comment by billbarni** [comment]
Sorry, I should have used the term 'Client Extention':

![image](https://user-images.githubusercontent.com/21037830/232758092-3588e64c-978b-4422-82ba-a3e60ba9c742.png)

By activating the Client Extention, I get the error.

Will investigate your new answer.

**Comment by billbarni** [comment]
I am already running the correct 0.1.0 version...

![image](https://user-images.githubusercontent.com/21037830/232774053-5457159b-8748-4cbc-8632-4fb8d72ba5ec.png)

![image](https://user-images.githubusercontent.com/21037830/232774277-eba40cdb-bed9-4b69-b76c-49d49cb4defc.png)

**Comment by billbarni** [comment]
This test in the Webpack changes the behavior of stuff... I am not sure how to better split it or how to do it in a way that both the 'Client Extention' and the 'Platform Bpmn' plugin work.
![image](https://user-images.githubusercontent.com/21037830/232775559-d097f298-fc5b-4c82-b3cd-62d24e97ea68.png)

**Comment by billbarni** [comment]
Maybe if I use the test for a directory containing the different modules? so a test for something like 'propertiesPanel/\.m?js$/' and then the other test 'client/\.js$/' or something like that?

I'm so sorry... my knowledge in webpack... JS is very low.

**Comment by pinussilvestrus** [comment]
I think, in general, if you have two plugins, it makes sense to divide this into several directories. As you said, you would have a bit more control over the config and in which directories they should go.

**Comment by billbarni** [comment]
But there is no fundamental explanation why it fails when in the same directory that I should be aware?

In a sense they are "the same plugin", since they are using each others code and so on... part of the same configuration...

I would like to understand why sometimes the react-icons work, and sometimes not... depending on the webpack config, and how to fix this.

**Comment by pinussilvestrus** [comment]
> I would like to understand why sometimes the react-icons work, and sometimes not

Maybe to start with this one. For which webpack config does it work for you? When you remove the `registerClientExtension`, it shows up correctly?

Which `resolve.alias` do you specify? According to your [posted branch](https://github.com/billbarni/camunda-modeler-plugin-react-test/blob/webpack_config_test/webpack.config.js#L71), it reads like

```js
 'react': 'camunda-modeler-plugin-helpers/vendor/@bpmn-io/properties-panel/preact/compat'
 ```
 
 it could be, that the React component in your Client extension stops working then, as it's not using the right React version anymore. I'm also wondering how this relates to the bpmn-js extension, as there is no React component. 
 
 My wild guess would be indeed, that it's mixing up React versions here. Did you try to remove the alias completely or use the one from the [plugin config](https://github.com/camunda/camunda-modeler-webpack-plugin/blob/main/src/config/react.config.js#L18)?

**Comment by billbarni** [comment]
https://github.com/billbarni/camunda-modeler-plugin-react-test/tree/webpack_config_test

I re-updated the branch. If you run it... it will work, the icon gets rendered.

If you un-comment this:

![image](https://user-images.githubusercontent.com/21037830/232784324-a45eb13a-d1b4-48ef-8351-ea3454ffe319.png)

I get:

`[plugin:ConfigDialog] Minified React error #284; visit https://reactjs.org/docs/error-decoder.html?invariant=284 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. `

and the Client Extension does not work.

**Comment by pinussilvestrus** [comment]
> My wild guess would be indeed, that it's mixing up React versions here. Did you try to remove the alias completely or use the one from the [plugin config](https://github.com/camunda/camunda-modeler-webpack-plugin/blob/main/src/config/react.config.js#L18)?

Did you have a chance to try that out?

**Comment by billbarni** [comment]
Yes. Does not work. Same errors or no rendering.

**Comment by pinussilvestrus** [comment]
It my relate to some internals on the Desktop Modeler then. A good idea would be to ask a broader audience [via the forum](https://forum.camunda.io/c/modeler/6). Maybe you'll find better advice over there.
